# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - touch .env
  build:
    commands:
      - make build
      - sam package --s3-bucket ${ARTIFACT_BUCKET}
                    --region ${REGION}
                    --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
    - parameters-production.json
cache:
  paths:
    - '*/**/.aws-sam/**/*'
    - '~/.cache/go-build/**'
